services:
  app:
    volumes:
      - ./tests/mocks:/srv/wog/scoring/storage
    networks:
      test-network:

  scores:
    volumes:
      - ./tests/mocks:/srv/wog/scoring/storage
    networks:
      test-network:

  tests:
    build:
      dockerfile: Dockerfile-test
      context: .
    depends_on:
      - scores
      - app
      - selenium-hub
    networks:
      test-network:

  chrome:
    image: selenium/node-chrome:4.21.0-20240522
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=20
    networks:
      test-network:

  edge:
    image: selenium/node-edge:4.21.0-20240522
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=20
    networks:
      test-network:

  firefox:
    image: selenium/node-firefox:4.21.0-20240522
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=20
    networks:
      test-network:

  selenium-hub:
    image: selenium/hub:4.21.0-20240522
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      test-network:

networks:
  test-network: