services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: "python cli.py"
    volumes:
      - ./scoring/storage:/srv/wog/scoring/storage

  scores:
    build:
      dockerfile: Dockerfile
      context: .
    command: "python -m flask run --host 0.0.0.0"
    volumes:
      - ./scoring/storage:/srv/wog/scoring/storage
    ports:
      - "8777:5000"
    networks:
      main:

networks:
  main: